### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-eva-lm#1]
Really cool job @eva-lm !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language of the page
- [x] Should the `.menu` element be a nonsemantics `div` or a rich semantic `nav` with `ul` and `li` (commonly used for our main navigation)
- [x] Humanize text in `alt` attributes, a sentence without the underscore may do the trick.

## CSS - box model
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)
- [x] It is not necessary to repeat `display: flex;` in `@media all and (min-width:768px){
` > `.header`

## CSS - other
- [ ] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles

## Good practices
- [x] Use relative routes like `./styles/main.css`.
- [x] Try to use imperative for your commit messages. Ex. - > Fix c
- [x] Indent and avoid extra white spaces to improve readability and avoid bugsentral text

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Hola Eva, el ejercicio está bastante bien, solo hay una pega que es la semántica del menú, pero en general puedes estar contenta con el resultado.

**Comment by migueldelmazo** [comment]
Hola @eva-lm cuando decimos: 

Avoid uppercase/capital on HTML texts, and br tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles

Queremos decir que el texto principal del main debe ser un h1, no un listado. Si sacas un rato por favor corrígelo.

**Comment by eva-lm** [comment]
Hola @migueldelmazo ya está arreglado :)

**Comment by migueldelmazo** [comment]
Ole, muchas gracias!!

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
